### ISSUE TITLE
Build Interface

### ISSUE THREAD

**Issue by rohanpillai20** [bhoomi2807/SE21-project#3]
@param userid: User id of the user

**Comment by bhoomi2807** [comment]
Genre should also be taken into consideration while building interface

**Comment by rohanpillai20** [comment]
Genre should be a dropdown menu, instead of a text box.

**Comment by shruti-k** [comment]
Yes. Genre is added as a dropdown menu in the UI.

**Comment by bhoomi2807** [comment]
Built and tested!
