### ISSUE TITLE
Add genre as another feature of filtering movies.

### ISSUE THREAD

**Issue by rohanpillai20** [bhoomi2807/SE21-project#4]

**Comment by AlishaShahane** [comment]
Genre is not enough to filter movies

**Comment by rohanpillai20** [comment]
Will add movie_ratings as a filter as well.

**Comment by shruti-k** [comment]
Is the genre field "required" in UI or can it be optional?

**Comment by AlishaShahane** [comment]
It is not a mandatory filed. It can be optional

**Comment by shruti-k** [comment]
Okay. Done that.

**Comment by bhoomi2807** [comment]
Verified
