### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by AlishaShahane** [bhoomi2807/SE21-project#8]

**Comment by poorvak7** [comment]
What software are we planning to use?

**Comment by rohanpillai20** [comment]
> What software are we planning to use?

Coveralls

**Comment by rohanpillai20** [comment]
Coveralls is not functioning as expected. @PNK27 Could you have a look into Code Climate's Code Coverage feature?

**Comment by bhoomi2807** [comment]
Checked the coverage! Its around 66%
